name: check_artisan
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  sms_autofill: ^2.4.0
  image_picker: ^1.0.8
  bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Home Screen.png
    - assets/icons/logo checkartisan 1.png
    - assets/icons/bro.png
    - assets/Buttons/Group 1.png
    - assets/icons/track.png
    - assets/icons/call.png
    - assets/icons/pana.png
    - assets/icons/reg screen.jpg
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/confirmation.png
    - assets/icons/otp.png
    - assets/icons/password_reset.png
    - assets/Buttons/edit.png
    - assets/Buttons/info.png
    - assets/Buttons/logout.png
    - assets/Buttons/password.png
    - assets/Buttons/update.png

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
          style: italic

flutter_native_splash:
  color: "#004D40F2"
  image: assets/icons/Home Screen.png
  fullscreen: true
